# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8163d4ef00caf70c986527e88c83c52c"
name = "Quote Flow - B2B Quotes"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/api/webhooks/shop-redact"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/api/webhooks/customers-redact"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/api/webhooks/customers-data-request"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_products,write_draft_orders,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
